# FILE: .github/workflows/fetch-logos.yml
name: Fetch and commit tool logos

on:
  workflow_dispatch: {}   # run manually from the Actions tab

permissions:
  contents: write         # needed to push changes back

jobs:
  fetch-logos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow beautifulsoup4 lxml

      - name: Ensure logo folder exists
        run: mkdir -p assets/logos

      - name: Run logo fetcher
        run: python scripts/fetch_logos.py

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(assets): fetch/update logos via workflow"
            git push
          else
            echo "No changes to commit."
          fi
